project:
  type: website

website:
  title: "Building Spatial Data Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - example-functions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
  error: true


